apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
  namespace: default
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://localhost:9411/api/v2/spans"
  metric:
    enabled: true
  accessControl:
    defaultAction: allow
    trustDomain: "public"
    policies:
    - appId: "tprm-backend"
      defaultAction: allow
      trustDomain: "public"
      namespace: "default"
    - appId: "tprm-frontend"
      defaultAction: allow
      trustDomain: "public"
      namespace: "default"
  features:
  - name: Actor.Reentrancy
    enabled: true
  - name: HotReload
    enabled: true